import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useCallback, useContext, useEffect, useState } from 'react';

export type Language = 'en' | 'ar';
const LANG_KEY = 'madarik_lang_v1';

const translations = {
  en: {
    // Mode select
    modeSelectTag: 'WELCOME TO MADARIK',
    modeSelectTitle: 'Choose Your Path',
    modeSelectSub: 'Select the experience that fits your financial goals. You can switch anytime from your profile.',
    businessTitle: 'Madarik for Business',
    businessDesc: 'Manage company cash flow, business banking, revenues, and expenses with AI-powered insights.',
    businessF1: 'Cash flow analytics',
    businessF2: 'Business banking',
    businessF3: 'AI financial advisor',
    personalTitle: 'Madarik Personal',
    personalDesc: 'Smart investing, behavioral AI scoring, emotion detection, and personal cards management.',
    personalF1: 'Behavioral AI score',
    personalF2: 'Portfolio tracking',
    personalF3: 'Smart insights',
    modeFooter: 'Trusted by 2,400+ businesses and investors across Saudi Arabia',
    // Login
    loginTitle: 'Log in',
    loginUserPlaceholder: 'Username or ID',
    loginPassPlaceholder: 'Password',
    loginRemember: 'Remember me',
    loginBtn: 'Log in',
    loginForgot: 'Forgot Your Credentials?',
    loginNoAccount: "Don't have an account?",
    loginSignUp: ' Sign up',
    loginContact: 'CONTACT US',
    loginCopyright: 'Madarik 2026. All rights reserved',
    // Signup
    signupTitle: 'Sign up',
    signupNationalId: 'National id / Iqama number',
    signupNationalIdPh: 'Fill your ID/Iqama',
    signupMobile: 'Mobile Number',
    signupEmail: 'Email',
    signupEmailPh: 'Fill your Email',
    signupFirstName: 'First Name',
    signupLastName: 'Last Name',
    signupUsername: 'Username',
    signupUsernamePh: 'Fill your Username',
    signupPassword: 'Password',
    signupPasswordPh: 'Fill your password',
    signupAgree: 'I Agree to the Terms And Conditions and confirm that I have read and understood the Privacy Notice',
    signupBtn: 'Sign up',
    signupHaveAccount: 'already have an account?',
    signupLogin: ' Log-in',
    // Modes
    businessMode: 'Business Mode',
    personalMode: 'Personal Mode',
    // Settings — shared
    settingsLanguage: 'Language',
    settingsLanguageValue: 'English',
    settingsNotifications: 'Notifications',
    settingsLogout: 'Log out',
    settingsSignOut: 'Sign Out',
    settingsSwitchBusiness: 'Switch to Business Mode',
    settingsSwitchPersonal: 'Switch to Personal Mode',
    settingsReferral: 'Referral Code',
    settingsVersion: 'Madarik v1.0.0',
    settingsSupport: 'Support',
    settingsHelp: 'Help',
    // Settings — Personal
    settingsPersonalInfo: 'Personal Information',
    settingsCards: 'Cards Management',
    settingsPrivacy: 'Privacy & Security',
    settingsBehavioral: 'Behavioral Assessment',
    settingsProfileTitle: 'Profile',
    // Settings — Business
    settingsAccount: 'Account',
    settingsCompanyDetails: 'Company Details',
    settingsPaymentMethods: 'Payment Methods',
    settingsBilling: 'Billing & Invoices',
    settingsPreferences: 'Preferences',
    settingsCurrency: 'Currency',
    settingsSecurity: 'Security',
    settingsChangePassword: 'Change Password',
    settingsBiometric: 'Biometric Login',
    settingsTwoFactor: 'Two-Factor Auth',
    // Home — Personal
    homeGoodMorning: 'GOOD MORNING',
    homeWelcomeBack: 'Welcome back,',
    homeBalance: 'Total Balance',
    homePortfolio: 'Portfolio',
    homeRecentTx: 'Recent Transactions',
    homeViewAll: 'View all',
    homeInvest: 'Investments',
    homeScore: 'Behavioral Score',
    homeSavings: 'Savings',
    homeCards: 'My Cards',
    // Home — Business
    homeRevenue: 'Revenue',
    homeExpenses: 'Expenses',
    homeCashflow: 'Cash Flow',
    homePayments: 'Upcoming Payments',
    homeActivity: 'Recent Activity',
    homeTotalBal: 'Total Business Balance',
    homeHealthScore: 'Health Score',
    homeAccounts: 'Accounts',
    homeAlerts: 'Alerts',
    // AI / Modrik screen
    aiOnline: 'AI Analyst · Online',
    aiAnalyzing: 'AI Analyst · Analyzing market sentiment...',
    aiTypePlaceholder: 'Ask Modrik anything...',
    aiTypePlaceholderPersonal: 'Type a message, or ask Modrik about your assets...',
    aiVolatilityAlert: 'Modrik: Market volatility detected. Emotional stability: 88%',
    aiProtect: 'Protect',
    aiCalculating: 'Modrik is calculating risks...',
    aiToday: 'TODAY',
    aiPersonalQ1: 'Yes, protect my portfolio',
    aiPersonalQ2: 'Show History',
    aiPersonalQ3: 'Talk it out',
    aiPersonalQ4: 'My behavioral score',
    aiBusinessQ1: 'Analyze cash flow',
    aiBusinessQ2: 'Reduce expenses',
    aiBusinessQ3: 'Loan eligibility',
    aiBusinessQ4: 'Revenue forecast',
    // Analytics screen
    analyticsTitle: 'Analytics',
    analyticsSubtitle: 'Financial overview · Jul 2026',
    analyticsRevenue: 'REVENUE',
    analyticsExpenses: 'EXPENSES',
    analyticsNetProfit: 'NET PROFIT',
    analyticsRevenueTrend: 'Revenue Trend',
    analyticsExpenseBreakdown: 'Expense Breakdown',
    analyticsHealthScore: 'Business Health Score',
    analyticsHealthDesc: 'Excellent performance this quarter',
    analyticsGrossMargin: 'Gross Margin',
    analyticsNetMargin: 'Net Margin',
    analyticsROI: 'ROI',
    analyticsBurnRate: 'Burn Rate',
    analyticsPayroll: 'Payroll',
    analyticsOperations: 'Operations',
    analyticsSuppliers: 'Suppliers',
    analyticsRentUtil: 'Rent & Utilities',
    analyticsOther: 'Other',
    // Cash Flow screen
    cashflowTitle: 'Cash Flow',
    cashflowSubtitle: '30-day forecast',
    cashflowExportPDF: 'Export PDF',
    cashflowMonthlyInflow: 'Monthly Inflow',
    cashflowMonthlyOutflow: 'Monthly Outflow',
    cashflowNetMonth: 'Net This Month',
    cashflow30DayLabel: '30-Day Net Forecast:',
    cashflowPositiveSurplus: 'Positive surplus expected',
    cashflow6Month: '6-Month Cash Flow',
    cashflowInflow: 'Inflow',
    cashflowOutflow: 'Outflow',
    cashflowRevenueUp: 'Revenue up 12% vs last quarter',
    cashflowModrikRec: 'Modrik AI Recommendation',
    cashflowModrikBody: 'Projected surplus of SAR 45,000 next month. Consider moving this to a high-yield business account to optimize working capital. Your cash runway is healthy at 4.2 months.',
    cashflowAskModrik: 'Ask Modrik for details',
    cashflowApplyFinancing: 'Apply\nFinancing',
    cashflowAIRec: 'AI\nRecommendations',
    cashflowFinancialReport: 'Financial\nReport',
    cashflowAskModrikShort: 'Ask\nModrik',
    // Notifications
    notifTitle: 'Notifications',
    notifMarkAllRead: 'Mark all read',
    notifSearchPh: 'Search notifications, bots, or assets...',
    notifFilterAll: 'All',
    notifFilterEmotional: 'Emotional',
    notifFilterInsights: 'Insights',
    notifFilterTransact: 'Transact',
    notifRecentActivity: 'RECENT ACTIVITY',
    notifUnread: 'UNREAD',
    notifEmpty: 'No notifications found',
    // AI Recommendations
    aiRecTitle: 'AI Recommendations',
    aiRecHighImpact: 'High Impact',
    aiRecMedium: 'Medium',
    aiRecInformational: 'Informational',
    aiRecTakeAction: 'Take Action',
    aiRecImpactHigh: 'High Impact',
    aiRecImpactMedium: 'Medium Impact',
    aiRecImpactLow: 'Low Impact',
    // AI Alerts
    aiAlertsTitle: 'Alerts',
    aiAlertsCritical: 'Critical',
    aiAlertsWarning: 'Warning',
    aiAlertsInfo: 'Info',
    // AI Report
    aiReportTitle: 'AI Financial Report',
    aiReportHealthScore: 'Business Health Score',
    aiReportHealthDesc: 'Excellent · Top 15% of businesses',
    aiReportMonthlyRevenue: 'Monthly Revenue',
    aiReportExportPDF: 'Export Full Report (PDF)',
    aiReportGrossRevenue: 'Gross Revenue',
    aiReportNetRevenue: 'Net Revenue',
    aiReportTotalExpenses: 'Total Expenses',
    aiReportNetProfit: 'Net Profit',
    aiReportProfitMargin: 'Profit Margin',
    aiReportCashOnHand: 'Cash on Hand',
    aiReportExecSummary: 'Executive Summary',
    aiReportRevenueAnalysis: 'Revenue Analysis',
    aiReportExpenseReview: 'Expense Review',
    aiReportCashFlowLiq: 'Cash Flow & Liquidity',
    aiReportQ4Outlook: 'Q4 2026 Outlook',
    // Loan Review
    loanTitle: 'Loan Review',
    loanReviewOffer: 'Review Offer',
    loanPreQualified: 'Pre-qualified',
    loanTotalAmount: 'TOTAL LOAN AMOUNT',
    loanAmountSub: 'Approved for expansion & growth',
    loanInterestRate: 'INTEREST RATE',
    loanFixedAnnual: 'Fixed Annual',
    loanTermPeriod: 'TERM PERIOD',
    loanMonthlyInst: 'Monthly Installments',
    loanMonthly: 'MONTHLY',
    loanDueOn5th: 'Due on 5th',
    loanTotalCost: 'TOTAL COST',
    loanIncProcessing: 'Inc. 0% Processing',
    loanGuaranteeTitle: 'Madarik Guarantee',
    loanGuaranteeSub: 'Transparent terms, no hidden fees.',
    loanG1: 'No early repayment penalties',
    loanG2: 'Automatic repayment from forecast',
    loanG3: 'Instant funds transfer upon confirmation',
    loanG4: 'Digital contract with e-signature',
    loanContinue: 'Continue to Confirm',
    loanBackRec: 'Back to Recommendations',
    // Upcoming Payments
    upcomingTitle: 'Upcoming Payments',
    upcomingTotalDue: 'TOTAL DUE THIS MONTH',
    upcomingUrgentBadge: 'URGENT',
    upcomingFilterAll: 'All',
    upcomingFilterUrgent: 'Urgent',
    upcomingFilterUpcoming: 'Upcoming',
    // Accounts
    accountsTitle: 'Business Accounts',
    accountsWelcomeSub: 'Manage all your business accounts in one place.',
    accountsTotalBalance: 'Total Business Balance',
    accountsAvailCash: 'AVAILABLE CASH',
    accountsTodayChange: "TODAY'S CHANGE",
    accountsTransfer: 'Transfer',
    accountsTransactions: 'Transactions',
    accountsAccountInfo: 'Account Info',
    accountsStatements: 'Statements',
    accountsYourAccounts: 'Your Accounts',
    accountsViewAll: 'View All',
    accountsCurrBalance: 'Current Balance',
    accountsActive: 'Active',
    accountsLastTx: 'LAST TRANSACTION',
    accountsInterestEarned: 'INTEREST EARNED',
    accountsNextPayroll: 'NEXT PAYROLL',
    accountsAvailCredit: 'AVAILABLE CREDIT',
    accountsNeedHelp: 'Need help with your accounts?',
    accountsHelpDesc: 'Ask Modrik about cash flow or transaction history.',
    accountsAskBtn: 'Ask Modrik',
    // Behavioral Assessment
    behavTitle: 'Behavior Assessment',
    behavSub: 'Answer a few questions so Modrik can understand your financial behavior and provide personalized investment recommendations.',
    behavFinancialProfile: 'Financial Profile',
    behavMonthlyIncome: 'MONTHLY INCOME',
    behavMonthlyExpenses: 'MONTHLY EXPENSES',
    behavCurrentSavings: 'CURRENT SAVINGS',
    behavCurrentInvestment: 'CURRENT INVESTMENT',
    behavInvExp: 'Investment Experience',
    behavBeginner: 'Beginner',
    behavIntermediate: 'Intermediate',
    behavAdvanced: 'Advanced',
    behavInvGoal: 'Investment Goal',
    behavGoal1: 'Wealth Growth',
    behavGoal2: 'Retirement',
    behavGoal3: 'Emergency Fund',
    behavGoal4: 'Passive Income',
    behavGoal5: 'Education',
    behavRiskTolerance: 'Risk Tolerance',
    behavConservative: 'Conservative',
    behavModerate: 'Moderate',
    behavAggressive: 'Aggressive',
    behavPsychProfile: 'Psychological Profile',
    behavLossQ: 'If your portfolio lost 20% in a month, how would you react?',
    behavLossR1: 'Sell everything immediately',
    behavLossR2: 'Wait and monitor carefully',
    behavLossR3: 'Buy more at a lower price',
    behavSocialQ: 'Do you make investment decisions based on social media trends?',
    behavSocialR1: 'Never, I do my own research',
    behavSocialR2: 'Sometimes for small amounts',
    behavSocialR3: 'Frequently to catch trends',
    behavKnowledgeQ: 'Rate your confidence in financial market knowledge (1-10)',
    behavKnowledgeRange: '1 = Novice, 10 = Expert',
    behavHoldingQ: 'What is your typical investment holding period?',
    behavHoldingR1: 'Less than 6 months',
    behavHoldingR2: '6 – 12 months',
    behavHoldingR3: 'More than 1 year',
    behavModrikNoteTitle: 'Modrik Engine',
    behavModrikNoteText: 'The Modrik neural engine analyzes your risk appetite and behavioral biases to construct a mathematically optimized portfolio tailored specifically to your psychological profile.',
    behavAnalyze: 'Analyze My Profile',
    behavAnalyzing: 'Analyzing...',
    behavResultTitle: 'Behavioral Score',
    behavResultBadge: 'Level: Excellent',
    behavResultDone: 'View Smart Insights',
    // Cash Flow Forecast page (separate from cashflow tab)
    cashFlowForecastTitle: 'Cash Flow Forecast',
    cashFlowInflows: 'INFLOWS',
    cashFlowOutflows: 'OUTFLOWS',
    cashFlowNetFlow: 'NET FLOW',
    cashFlowPositive: 'Positive',
    cashFlowChartTitle: 'Cash Flow Chart',
    cashFlowLegendInflows: 'Inflows',
    cashFlowLegendOutflows: 'Outflows',
    cashFlowInflowSources: 'Inflow Sources',
    cashFlowOutflowCat: 'Outflow Categories',
    cashFlowModrikInsight: 'Modrik AI Insight',
    cashFlowInsightBody: 'A 4.2% declining trend is expected next 30 days due to seasonal supplier payments. Your strong inflow coverage ratio (1.27x) means your business remains liquid. Consider delaying non-critical purchases to preserve SAR 45,000+ in operating buffer.',
    cashFlowClientRevenue: 'Client Revenue',
    cashFlowServiceFees: 'Service Fees',
    cashFlowInvestments: 'Investments',
    cashFlowPayroll: 'Payroll',
    cashFlowSuppliers: 'Suppliers',
    cashFlowOperations: 'Operations',
    cashFlowOther: 'Other',
  },
  ar: {
    // Mode select
    modeSelectTag: 'أهلاً بك في مدارك',
    modeSelectTitle: 'اختر مسارك',
    modeSelectSub: 'حدد التجربة التي تناسب أهدافك المالية. يمكنك التبديل في أي وقت من ملفك الشخصي.',
    businessTitle: 'مدارك للأعمال',
    businessDesc: 'إدارة التدفق النقدي للشركة، الخدمات المصرفية التجارية، الإيرادات والمصروفات بالذكاء الاصطناعي.',
    businessF1: 'تحليلات التدفق النقدي',
    businessF2: 'الخدمات المصرفية',
    businessF3: 'مستشار مالي ذكي',
    personalTitle: 'مدارك الشخصي',
    personalDesc: 'الاستثمار الذكي، التقييم السلوكي بالذكاء الاصطناعي، اكتشاف المشاعر وإدارة البطاقات الشخصية.',
    personalF1: 'التقييم السلوكي',
    personalF2: 'تتبع المحفظة',
    personalF3: 'رؤى ذكية',
    modeFooter: 'موثوق به من قبل أكثر من 2,400 شركة ومستثمر في المملكة العربية السعودية',
    // Login
    loginTitle: 'تسجيل الدخول',
    loginUserPlaceholder: 'اسم المستخدم أو الهوية',
    loginPassPlaceholder: 'كلمة المرور',
    loginRemember: 'تذكرني',
    loginBtn: 'دخول',
    loginForgot: 'نسيت بيانات الدخول؟',
    loginNoAccount: 'ليس لديك حساب؟',
    loginSignUp: ' سجّل الآن',
    loginContact: 'تواصل معنا',
    loginCopyright: 'مدارك 2026. جميع الحقوق محفوظة',
    // Signup
    signupTitle: 'إنشاء حساب',
    signupNationalId: 'رقم الهوية الوطنية / الإقامة',
    signupNationalIdPh: 'أدخل رقم هويتك',
    signupMobile: 'رقم الجوال',
    signupEmail: 'البريد الإلكتروني',
    signupEmailPh: 'أدخل بريدك الإلكتروني',
    signupFirstName: 'الاسم الأول',
    signupLastName: 'اسم العائلة',
    signupUsername: 'اسم المستخدم',
    signupUsernamePh: 'أدخل اسم المستخدم',
    signupPassword: 'كلمة المرور',
    signupPasswordPh: 'أدخل كلمة المرور',
    signupAgree: 'أوافق على الشروط والأحكام وأؤكد أنني قرأت وفهمت إشعار الخصوصية',
    signupBtn: 'تسجيل',
    signupHaveAccount: 'لديك حساب بالفعل؟',
    signupLogin: ' سجّل دخولك',
    // Modes
    businessMode: 'وضع الأعمال',
    personalMode: 'الوضع الشخصي',
    // Settings — shared
    settingsLanguage: 'اللغة',
    settingsLanguageValue: 'العربية',
    settingsNotifications: 'الإشعارات',
    settingsLogout: 'تسجيل الخروج',
    settingsSignOut: 'تسجيل الخروج',
    settingsSwitchBusiness: 'التحويل إلى وضع الأعمال',
    settingsSwitchPersonal: 'التحويل إلى الوضع الشخصي',
    settingsReferral: 'رمز الإحالة',
    settingsVersion: 'مدارك v1.0.0',
    settingsSupport: 'الدعم الفني',
    settingsHelp: 'المساعدة',
    // Settings — Personal
    settingsPersonalInfo: 'المعلومات الشخصية',
    settingsCards: 'إدارة البطاقات',
    settingsPrivacy: 'الخصوصية والأمان',
    settingsBehavioral: 'التقييم السلوكي',
    settingsProfileTitle: 'الملف الشخصي',
    // Settings — Business
    settingsAccount: 'الحساب',
    settingsCompanyDetails: 'تفاصيل الشركة',
    settingsPaymentMethods: 'طرق الدفع',
    settingsBilling: 'الفواتير',
    settingsPreferences: 'التفضيلات',
    settingsCurrency: 'العملة',
    settingsSecurity: 'الأمان',
    settingsChangePassword: 'تغيير كلمة المرور',
    settingsBiometric: 'تسجيل الدخول البيومتري',
    settingsTwoFactor: 'المصادقة الثنائية',
    // Home — Personal
    homeGoodMorning: 'صباح الخير',
    homeWelcomeBack: 'مرحباً بعودتك،',
    homeBalance: 'الرصيد الإجمالي',
    homePortfolio: 'المحفظة',
    homeRecentTx: 'المعاملات الأخيرة',
    homeViewAll: 'عرض الكل',
    homeInvest: 'الاستثمارات',
    homeScore: 'التقييم السلوكي',
    homeSavings: 'المدخرات',
    homeCards: 'بطاقاتي',
    // Home — Business
    homeRevenue: 'الإيرادات',
    homeExpenses: 'المصروفات',
    homeCashflow: 'التدفق النقدي',
    homePayments: 'المدفوعات القادمة',
    homeActivity: 'النشاط الأخير',
    homeTotalBal: 'إجمالي رصيد الأعمال',
    homeHealthScore: 'نقاط الصحة',
    homeAccounts: 'الحسابات',
    homeAlerts: 'التنبيهات',
    // AI / Modrik screen
    aiOnline: 'محلل ذكي · متصل',
    aiAnalyzing: 'محلل ذكي · يحلل معنويات السوق...',
    aiTypePlaceholder: 'اسأل مدرك أي شيء...',
    aiTypePlaceholderPersonal: 'اكتب رسالة، أو اسأل مدرك عن أصولك...',
    aiVolatilityAlert: 'مدرك: تم رصد تقلب في السوق. الاستقرار العاطفي: 88%',
    aiProtect: 'حماية',
    aiCalculating: 'مدرك يحسب المخاطر...',
    aiToday: 'اليوم',
    aiPersonalQ1: 'نعم، احمِ محفظتي',
    aiPersonalQ2: 'عرض السجل',
    aiPersonalQ3: 'تحدث معي',
    aiPersonalQ4: 'تقييمي السلوكي',
    aiBusinessQ1: 'تحليل التدفق النقدي',
    aiBusinessQ2: 'تقليل المصروفات',
    aiBusinessQ3: 'أهلية القرض',
    aiBusinessQ4: 'توقعات الإيرادات',
    // Analytics screen
    analyticsTitle: 'التحليلات',
    analyticsSubtitle: 'نظرة مالية · يوليو 2026',
    analyticsRevenue: 'الإيرادات',
    analyticsExpenses: 'المصروفات',
    analyticsNetProfit: 'صافي الربح',
    analyticsRevenueTrend: 'اتجاه الإيرادات',
    analyticsExpenseBreakdown: 'تفصيل المصروفات',
    analyticsHealthScore: 'مؤشر صحة الأعمال',
    analyticsHealthDesc: 'أداء ممتاز هذا الربع',
    analyticsGrossMargin: 'هامش الربح الإجمالي',
    analyticsNetMargin: 'هامش الربح الصافي',
    analyticsROI: 'العائد على الاستثمار',
    analyticsBurnRate: 'معدل الإنفاق',
    analyticsPayroll: 'الرواتب',
    analyticsOperations: 'العمليات',
    analyticsSuppliers: 'الموردون',
    analyticsRentUtil: 'الإيجار والمرافق',
    analyticsOther: 'أخرى',
    // Cash Flow screen
    cashflowTitle: 'التدفق النقدي',
    cashflowSubtitle: 'توقعات 30 يوم',
    cashflowExportPDF: 'تصدير PDF',
    cashflowMonthlyInflow: 'التدفق الداخل الشهري',
    cashflowMonthlyOutflow: 'التدفق الخارج الشهري',
    cashflowNetMonth: 'الصافي هذا الشهر',
    cashflow30DayLabel: 'توقعات الصافي 30 يوم:',
    cashflowPositiveSurplus: 'فائض إيجابي متوقع',
    cashflow6Month: 'التدفق النقدي 6 أشهر',
    cashflowInflow: 'داخل',
    cashflowOutflow: 'خارج',
    cashflowRevenueUp: 'الإيرادات ارتفعت 12% مقارنة بالربع الماضي',
    cashflowModrikRec: 'توصية مدرك الذكي',
    cashflowModrikBody: 'فائض متوقع 45,000 ريال الشهر القادم. فكر في نقله إلى حساب أعمال عالي العائد لتحسين رأس المال العامل. مدتك النقدية صحية بـ 4.2 شهر.',
    cashflowAskModrik: 'اسأل مدرك للتفاصيل',
    cashflowApplyFinancing: 'تقدم\nللتمويل',
    cashflowAIRec: 'توصيات\nالذكاء',
    cashflowFinancialReport: 'التقرير\nالمالي',
    cashflowAskModrikShort: 'اسأل\nمدرك',
    // Notifications
    notifTitle: 'الإشعارات',
    notifMarkAllRead: 'تحديد الكل كمقروء',
    notifSearchPh: 'البحث في الإشعارات...',
    notifFilterAll: 'الكل',
    notifFilterEmotional: 'عاطفي',
    notifFilterInsights: 'رؤى',
    notifFilterTransact: 'معاملات',
    notifRecentActivity: 'النشاط الأخير',
    notifUnread: 'غير مقروء',
    notifEmpty: 'لا توجد إشعارات',
    // AI Recommendations
    aiRecTitle: 'توصيات الذكاء الاصطناعي',
    aiRecHighImpact: 'تأثير عالٍ',
    aiRecMedium: 'متوسط',
    aiRecInformational: 'معلوماتي',
    aiRecTakeAction: 'اتخذ إجراء',
    aiRecImpactHigh: 'تأثير عالٍ',
    aiRecImpactMedium: 'تأثير متوسط',
    aiRecImpactLow: 'تأثير منخفض',
    // AI Alerts
    aiAlertsTitle: 'التنبيهات',
    aiAlertsCritical: 'حرج',
    aiAlertsWarning: 'تحذير',
    aiAlertsInfo: 'معلومة',
    // AI Report
    aiReportTitle: 'التقرير المالي الذكي',
    aiReportHealthScore: 'مؤشر صحة الأعمال',
    aiReportHealthDesc: 'ممتاز · أفضل 15% من الشركات',
    aiReportMonthlyRevenue: 'الإيرادات الشهرية',
    aiReportExportPDF: 'تصدير التقرير كاملاً (PDF)',
    aiReportGrossRevenue: 'إجمالي الإيرادات',
    aiReportNetRevenue: 'صافي الإيرادات',
    aiReportTotalExpenses: 'إجمالي المصروفات',
    aiReportNetProfit: 'صافي الربح',
    aiReportProfitMargin: 'هامش الربح',
    aiReportCashOnHand: 'النقد المتاح',
    aiReportExecSummary: 'الملخص التنفيذي',
    aiReportRevenueAnalysis: 'تحليل الإيرادات',
    aiReportExpenseReview: 'مراجعة المصروفات',
    aiReportCashFlowLiq: 'التدفق النقدي والسيولة',
    aiReportQ4Outlook: 'توقعات الربع الرابع 2026',
    // Loan Review
    loanTitle: 'مراجعة القرض',
    loanReviewOffer: 'مراجعة العرض',
    loanPreQualified: 'مؤهل مسبقاً',
    loanTotalAmount: 'إجمالي مبلغ القرض',
    loanAmountSub: 'معتمد للتوسع والنمو',
    loanInterestRate: 'معدل الفائدة',
    loanFixedAnnual: 'سنوي ثابت',
    loanTermPeriod: 'مدة القرض',
    loanMonthlyInst: 'أقساط شهرية',
    loanMonthly: 'شهرياً',
    loanDueOn5th: 'يستحق في الخامس',
    loanTotalCost: 'التكلفة الإجمالية',
    loanIncProcessing: 'شامل 0% رسوم',
    loanGuaranteeTitle: 'ضمان مدارك',
    loanGuaranteeSub: 'شروط شفافة، لا رسوم خفية.',
    loanG1: 'لا غرامات سداد مبكر',
    loanG2: 'سداد تلقائي من التوقعات',
    loanG3: 'تحويل فوري عند التأكيد',
    loanG4: 'عقد رقمي بتوقيع إلكتروني',
    loanContinue: 'المتابعة للتأكيد',
    loanBackRec: 'العودة للتوصيات',
    // Upcoming Payments
    upcomingTitle: 'المدفوعات القادمة',
    upcomingTotalDue: 'إجمالي المستحق هذا الشهر',
    upcomingUrgentBadge: 'عاجل',
    upcomingFilterAll: 'الكل',
    upcomingFilterUrgent: 'عاجل',
    upcomingFilterUpcoming: 'قادم',
    // Accounts
    accountsTitle: 'حسابات الأعمال',
    accountsWelcomeSub: 'إدارة جميع حسابات أعمالك في مكان واحد.',
    accountsTotalBalance: 'إجمالي رصيد الأعمال',
    accountsAvailCash: 'النقد المتاح',
    accountsTodayChange: 'تغيير اليوم',
    accountsTransfer: 'تحويل',
    accountsTransactions: 'المعاملات',
    accountsAccountInfo: 'بيانات الحساب',
    accountsStatements: 'الكشوفات',
    accountsYourAccounts: 'حساباتك',
    accountsViewAll: 'عرض الكل',
    accountsCurrBalance: 'الرصيد الحالي',
    accountsActive: 'نشط',
    accountsLastTx: 'آخر معاملة',
    accountsInterestEarned: 'الفائدة المكتسبة',
    accountsNextPayroll: 'الرواتب القادمة',
    accountsAvailCredit: 'الائتمان المتاح',
    accountsNeedHelp: 'تحتاج مساعدة في حساباتك؟',
    accountsHelpDesc: 'اسأل مدرك عن التدفق النقدي أو سجل المعاملات.',
    accountsAskBtn: 'اسأل مدرك',
    // Behavioral Assessment
    behavTitle: 'تقييم السلوك',
    behavSub: 'أجب على بعض الأسئلة حتى يتمكن مدرك من فهم سلوكك المالي وتقديم توصيات استثمارية مخصصة.',
    behavFinancialProfile: 'الملف المالي',
    behavMonthlyIncome: 'الدخل الشهري',
    behavMonthlyExpenses: 'المصروفات الشهرية',
    behavCurrentSavings: 'المدخرات الحالية',
    behavCurrentInvestment: 'الاستثمار الحالي',
    behavInvExp: 'خبرة الاستثمار',
    behavBeginner: 'مبتدئ',
    behavIntermediate: 'متوسط',
    behavAdvanced: 'متقدم',
    behavInvGoal: 'هدف الاستثمار',
    behavGoal1: 'نمو الثروة',
    behavGoal2: 'التقاعد',
    behavGoal3: 'صندوق الطوارئ',
    behavGoal4: 'الدخل السلبي',
    behavGoal5: 'التعليم',
    behavRiskTolerance: 'تحمّل المخاطر',
    behavConservative: 'محافظ',
    behavModerate: 'معتدل',
    behavAggressive: 'عدواني',
    behavPsychProfile: 'الملف النفسي',
    behavLossQ: 'إذا خسرت محفظتك 20% في شهر، كيف ستتصرف؟',
    behavLossR1: 'بيع كل شيء فوراً',
    behavLossR2: 'الانتظار والمراقبة بعناية',
    behavLossR3: 'شراء المزيد بسعر أقل',
    behavSocialQ: 'هل تتخذ قرارات استثمارية بناءً على اتجاهات وسائل التواصل؟',
    behavSocialR1: 'أبداً، أقوم ببحثي الخاص',
    behavSocialR2: 'أحياناً لمبالغ صغيرة',
    behavSocialR3: 'كثيراً لاستغلال الاتجاهات',
    behavKnowledgeQ: 'قيّم ثقتك في معرفة الأسواق المالية (1-10)',
    behavKnowledgeRange: '1 = مبتدئ، 10 = خبير',
    behavHoldingQ: 'ما هي فترة الاحتفاظ النموذجية لاستثماراتك؟',
    behavHoldingR1: 'أقل من 6 أشهر',
    behavHoldingR2: '6 – 12 شهراً',
    behavHoldingR3: 'أكثر من سنة',
    behavModrikNoteTitle: 'محرك مدرك',
    behavModrikNoteText: 'يحلل محرك مدرك العصبي شهيتك للمخاطر وتحيزاتك السلوكية لبناء محفظة محسّنة رياضياً مصمّمة خصيصاً لملفك النفسي.',
    behavAnalyze: 'تحليل ملفي',
    behavAnalyzing: 'جارٍ التحليل...',
    behavResultTitle: 'التقييم السلوكي',
    behavResultBadge: 'المستوى: ممتاز',
    behavResultDone: 'عرض الرؤى الذكية',
    // Cash Flow Forecast page
    cashFlowForecastTitle: 'توقعات التدفق النقدي',
    cashFlowInflows: 'التدفقات الداخلة',
    cashFlowOutflows: 'التدفقات الخارجة',
    cashFlowNetFlow: 'الصافي',
    cashFlowPositive: 'إيجابي',
    cashFlowChartTitle: 'مخطط التدفق النقدي',
    cashFlowLegendInflows: 'داخل',
    cashFlowLegendOutflows: 'خارج',
    cashFlowInflowSources: 'مصادر التدفق الداخل',
    cashFlowOutflowCat: 'فئات التدفق الخارج',
    cashFlowModrikInsight: 'رؤية مدرك الذكية',
    cashFlowInsightBody: 'انخفاض بنسبة 4.2% متوقع خلال 30 يوماً بسبب مدفوعات الموردين الموسمية. نسبة تغطية التدفقات القوية (1.27x) تضمن سيولة أعمالك. فكر في تأجيل المشتريات غير الحيوية للحفاظ على 45,000+ ريال كاحتياطي تشغيلي.',
    cashFlowClientRevenue: 'إيرادات العملاء',
    cashFlowServiceFees: 'رسوم الخدمات',
    cashFlowInvestments: 'الاستثمارات',
    cashFlowPayroll: 'الرواتب',
    cashFlowSuppliers: 'الموردون',
    cashFlowOperations: 'العمليات',
    cashFlowOther: 'أخرى',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: TranslationKey) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  // Load persisted language on mount
  useEffect(() => {
    AsyncStorage.getItem(LANG_KEY)
      .then(val => { if (val === 'en' || val === 'ar') setLanguage(val); })
      .catch(() => {});
  }, []);

  const toggleLanguage = useCallback(() => {
    setLanguage(l => {
      const next = l === 'en' ? 'ar' : 'en';
      AsyncStorage.setItem(LANG_KEY, next).catch(() => {});
      return next;
    });
  }, []);

  const t = useCallback(
    (key: TranslationKey): string => translations[language][key] as string,
    [language],
  );

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t, isRTL: language === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
