import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useCallback, useContext, useEffect, useState } from 'react';

export type Language = 'en' | 'ar';
const LANG_KEY = 'madarik_lang_v1';

const translations = {
  en: {
    // Mode select
    modeSelectTag: 'WELCOME TO MADARIK',
    modeSelectTitle: 'Choose Your Path',
    modeSelectSub: 'Select the experience that fits your financial goals. You can switch anytime from your profile.',
    businessTitle: 'Madarik for Business',
    businessDesc: 'Manage company cash flow, business banking, revenues, and expenses with AI-powered insights.',
    businessF1: 'Cash flow analytics',
    businessF2: 'Business banking',
    businessF3: 'AI financial advisor',
    personalTitle: 'Madarik Personal',
    personalDesc: 'Smart investing, behavioral AI scoring, emotion detection, and personal cards management.',
    personalF1: 'Behavioral AI score',
    personalF2: 'Portfolio tracking',
    personalF3: 'Smart insights',
    modeFooter: 'Trusted by 2,400+ businesses and investors across Saudi Arabia',
    // Login
    loginTitle: 'Log in',
    loginUserPlaceholder: 'Username or ID',
    loginPassPlaceholder: 'Password',
    loginRemember: 'Remember me',
    loginBtn: 'Log in',
    loginForgot: 'Forgot Your Credentials?',
    loginNoAccount: "Don't have an account?",
    loginSignUp: ' Sign up',
    loginContact: 'CONTACT US',
    loginCopyright: 'Madarik 2026. All rights reserved',
    // Signup
    signupTitle: 'Sign up',
    signupNationalId: 'National id / Iqama number',
    signupNationalIdPh: 'Fill your ID/Iqama',
    signupMobile: 'Mobile Number',
    signupEmail: 'Email',
    signupEmailPh: 'Fill your Email',
    signupFirstName: 'First Name',
    signupLastName: 'Last Name',
    signupUsername: 'Username',
    signupUsernamePh: 'Fill your Username',
    signupPassword: 'Password',
    signupPasswordPh: 'Fill your password',
    signupAgree: 'I Agree to the Terms And Conditions and confirm that I have read and understood the Privacy Notice',
    signupBtn: 'Sign up',
    signupHaveAccount: 'already have an account?',
    signupLogin: ' Log-in',
    // Signup validation errors
    validRequired: 'This field is required',
    validNationalIdDigits: 'National ID must contain digits only',
    validNationalIdMin: 'National ID must be at least 10 digits',
    validNationalIdTaken: 'This National ID is already registered',
    validEmailFormat: 'Please enter a valid email address (e.g. name@domain.com)',
    validEmailTaken: 'This email is already registered',
    validMobileDigits: 'Mobile must contain digits only',
    validMobileLen: 'Mobile number must be 9 digits and start with 5',
    validMobileTaken: 'This mobile number is already registered',
    validUsernameChars: 'Only letters, numbers and underscores allowed — no spaces or special characters',
    validUsernameTaken: 'This username is already taken',
    validPassLen: 'Password must be at least 8 characters',
    validPassUpper: 'Must include an uppercase letter (A-Z)',
    validPassLower: 'Must include a lowercase letter (a-z)',
    validPassDigit: 'Must include a number (0-9)',
    validPassSpecial: 'Must include a special character (e.g. !@#$%)',
    // Modes
    businessMode: 'Business Mode',
    personalMode: 'Personal Mode',
    // Settings — shared
    settingsLanguage: 'Language',
    settingsLanguageValue: 'English',
    settingsNotifications: 'Notifications',
    settingsLogout: 'Log out',
    settingsSignOut: 'Sign Out',
    settingsSwitchBusiness: 'Switch to Business Mode',
    settingsSwitchPersonal: 'Switch to Personal Mode',
    settingsReferral: 'Referral Code',
    settingsVersion: 'Madarik v1.0.0',
    settingsSupport: 'Support',
    settingsHelp: 'Help',
    // Settings — Personal
    settingsPersonalInfo: 'Personal Information',
    settingsCards: 'Cards Management',
    settingsPrivacy: 'Privacy & Security',
    settingsBehavioral: 'Behavioral Assessment',
    settingsProfileTitle: 'Profile',
    // Settings — Business
    settingsAccount: 'Account',
    settingsCompanyDetails: 'Company Details',
    settingsPaymentMethods: 'Payment Methods',
    settingsBilling: 'Billing & Invoices',
    settingsPreferences: 'Preferences',
    settingsCurrency: 'Currency',
    settingsSecurity: 'Security',
    settingsChangePassword: 'Change Password',
    settingsBiometric: 'Biometric Login',
    settingsTwoFactor: 'Two-Factor Auth',
    // Home — Personal
    homeGoodMorning: 'GOOD MORNING',
    homeWelcomeBack: 'Welcome back,',
    homeBalance: 'Total Balance',
    homePortfolio: 'Portfolio',
    homeRecentTx: 'Recent Transactions',
    homeViewAll: 'View all',
    homeInvest: 'Investments',
    homeScore: 'Behavioral Score',
    homeSavings: 'Savings',
    homeCards: 'My Cards',
    // Home — Business
    homeRevenue: 'Revenue',
    homeExpenses: 'Expenses',
    homeCashflow: 'Cash Flow',
    homePayments: 'Upcoming Payments',
    homeActivity: 'Recent Activity',
    homeTotalBal: 'Total Business Balance',
    homeHealthScore: 'Health Score',
    homeAccounts: 'Accounts',
    homeAlerts: 'Alerts',
    // AI / Modrik screen
    aiOnline: 'AI Analyst · Online',
    aiAnalyzing: 'AI Analyst · Analyzing market sentiment...',
    aiTypePlaceholder: 'Ask Modrik anything...',
    aiTypePlaceholderPersonal: 'Type a message, or ask Modrik about your assets...',
    aiVolatilityAlert: 'Modrik: Market volatility detected. Emotional stability: 88%',
    aiProtect: 'Protect',
    aiCalculating: 'Modrik is calculating risks...',
    aiToday: 'TODAY',
    aiPersonalQ1: 'Yes, protect my portfolio',
    aiPersonalQ2: 'Show History',
    aiPersonalQ3: 'Talk it out',
    aiPersonalQ4: 'My behavioral score',
    aiBusinessQ1: 'Analyze cash flow',
    aiBusinessQ2: 'Reduce expenses',
    aiBusinessQ3: 'Loan eligibility',
    aiBusinessQ4: 'Revenue forecast',
    // Analytics screen
    analyticsTitle: 'Analytics',
    analyticsSubtitle: 'Financial overview · Jul 2026',
    analyticsRevenue: 'REVENUE',
    analyticsExpenses: 'EXPENSES',
    analyticsNetProfit: 'NET PROFIT',
    analyticsRevenueTrend: 'Revenue Trend',
    analyticsExpenseBreakdown: 'Expense Breakdown',
    analyticsHealthScore: 'Business Health Score',
    analyticsHealthDesc: 'Excellent performance this quarter',
    analyticsGrossMargin: 'Gross Margin',
    analyticsNetMargin: 'Net Margin',
    analyticsROI: 'ROI',
    analyticsBurnRate: 'Burn Rate',
    analyticsPayroll: 'Payroll',
    analyticsOperations: 'Operations',
    analyticsSuppliers: 'Suppliers',
    analyticsRentUtil: 'Rent & Utilities',
    analyticsOther: 'Other',
    // Cash Flow screen
    cashflowTitle: 'Cash Flow',
    cashflowSubtitle: '30-day forecast',
    cashflowExportPDF: 'Export PDF',
    cashflowMonthlyInflow: 'Monthly Inflow',
    cashflowMonthlyOutflow: 'Monthly Outflow',
    cashflowNetMonth: 'Net This Month',
    cashflow30DayLabel: '30-Day Net Forecast:',
    cashflowPositiveSurplus: 'Positive surplus expected',
    cashflow6Month: '6-Month Cash Flow',
    cashflowInflow: 'Inflow',
    cashflowOutflow: 'Outflow',
    cashflowRevenueUp: 'Revenue up 12% vs last quarter',
    cashflowModrikRec: 'Modrik AI Recommendation',
    cashflowModrikBody: 'Projected surplus of SAR 45,000 next month. Consider moving this to a high-yield business account to optimize working capital. Your cash runway is healthy at 4.2 months.',
    cashflowAskModrik: 'Ask Modrik for details',
    cashflowApplyFinancing: 'Apply\nFinancing',
    cashflowAIRec: 'AI\nRecommendations',
    cashflowFinancialReport: 'Financial\nReport',
    cashflowAskModrikShort: 'Ask\nModrik',
    // Notifications
    notifTitle: 'Notifications',
    notifMarkAllRead: 'Mark all read',
    notifSearchPh: 'Search notifications, bots, or assets...',
    notifFilterAll: 'All',
    notifFilterEmotional: 'Emotional',
    notifFilterInsights: 'Insights',
    notifFilterTransact: 'Transact',
    notifRecentActivity: 'RECENT ACTIVITY',
    notifUnread: 'UNREAD',
    notifEmpty: 'No notifications found',
    // AI Recommendations
    aiRecTitle: 'AI Recommendations',
    aiRecHighImpact: 'High Impact',
    aiRecMedium: 'Medium',
    aiRecInformational: 'Informational',
    aiRecTakeAction: 'Take Action',
    aiRecImpactHigh: 'High Impact',
    aiRecImpactMedium: 'Medium Impact',
    aiRecImpactLow: 'Low Impact',
    // AI Alerts
    aiAlertsTitle: 'Alerts',
    aiAlertsCritical: 'Critical',
    aiAlertsWarning: 'Warning',
    aiAlertsInfo: 'Info',
    // AI Report
    aiReportTitle: 'AI Financial Report',
    aiReportHealthScore: 'Business Health Score',
    aiReportHealthDesc: 'Excellent · Top 15% of businesses',
    aiReportMonthlyRevenue: 'Monthly Revenue',
    aiReportExportPDF: 'Export Full Report (PDF)',
    aiReportGrossRevenue: 'Gross Revenue',
    aiReportNetRevenue: 'Net Revenue',
    aiReportTotalExpenses: 'Total Expenses',
    aiReportNetProfit: 'Net Profit',
    aiReportProfitMargin: 'Profit Margin',
    aiReportCashOnHand: 'Cash on Hand',
    aiReportExecSummary: 'Executive Summary',
    aiReportRevenueAnalysis: 'Revenue Analysis',
    aiReportExpenseReview: 'Expense Review',
    aiReportCashFlowLiq: 'Cash Flow & Liquidity',
    aiReportQ4Outlook: 'Q4 2026 Outlook',
    // Loan Review
    loanTitle: 'Loan Review',
    loanReviewOffer: 'Review Offer',
    loanPreQualified: 'Pre-qualified',
    loanTotalAmount: 'TOTAL LOAN AMOUNT',
    loanAmountSub: 'Approved for expansion & growth',
    loanInterestRate: 'INTEREST RATE',
    loanFixedAnnual: 'Fixed Annual',
    loanTermPeriod: 'TERM PERIOD',
    loanMonthlyInst: 'Monthly Installments',
    loanMonthly: 'MONTHLY',
    loanDueOn5th: 'Due on 5th',
    loanTotalCost: 'TOTAL COST',
    loanIncProcessing: 'Inc. 0% Processing',
    loanGuaranteeTitle: 'Madarik Guarantee',
    loanGuaranteeSub: 'Transparent terms, no hidden fees.',
    loanG1: 'No early repayment penalties',
    loanG2: 'Automatic repayment from forecast',
    loanG3: 'Instant funds transfer upon confirmation',
    loanG4: 'Digital contract with e-signature',
    loanContinue: 'Continue to Confirm',
    loanBackRec: 'Back to Recommendations',
    // Upcoming Payments
    upcomingTitle: 'Upcoming Payments',
    upcomingTotalDue: 'TOTAL DUE THIS MONTH',
    upcomingUrgentBadge: 'URGENT',
    upcomingFilterAll: 'All',
    upcomingFilterUrgent: 'Urgent',
    upcomingFilterUpcoming: 'Upcoming',
    // Accounts
    accountsTitle: 'Business Accounts',
    accountsWelcomeSub: 'Manage all your business accounts in one place.',
    accountsTotalBalance: 'Total Business Balance',
    accountsAvailCash: 'AVAILABLE CASH',
    accountsTodayChange: "TODAY'S CHANGE",
    accountsTransfer: 'Transfer',
    accountsTransactions: 'Transactions',
    accountsAccountInfo: 'Account Info',
    accountsStatements: 'Statements',
    accountsYourAccounts: 'Your Accounts',
    accountsViewAll: 'View All',
    accountsCurrBalance: 'Current Balance',
    accountsActive: 'Active',
    accountsLastTx: 'LAST TRANSACTION',
    accountsInterestEarned: 'INTEREST EARNED',
    accountsNextPayroll: 'NEXT PAYROLL',
    accountsAvailCredit: 'AVAILABLE CREDIT',
    accountsNeedHelp: 'Need help with your accounts?',
    accountsHelpDesc: 'Ask Modrik about cash flow or transaction history.',
    accountsAskBtn: 'Ask Modrik',
    // Behavioral Assessment
    behavTitle: 'Behavior Assessment',
    behavSub: 'Answer a few questions so Modrik can understand your financial behavior and provide personalized investment recommendations.',
    behavFinancialProfile: 'Financial Profile',
    behavMonthlyIncome: 'MONTHLY INCOME',
    behavMonthlyExpenses: 'MONTHLY EXPENSES',
    behavCurrentSavings: 'CURRENT SAVINGS',
    behavCurrentInvestment: 'CURRENT INVESTMENT',
    behavInvExp: 'Investment Experience',
    behavBeginner: 'Beginner',
    behavIntermediate: 'Intermediate',
    behavAdvanced: 'Advanced',
    behavInvGoal: 'Investment Goal',
    behavGoal1: 'Wealth Growth',
    behavGoal2: 'Retirement',
    behavGoal3: 'Emergency Fund',
    behavGoal4: 'Passive Income',
    behavGoal5: 'Education',
    behavRiskTolerance: 'Risk Tolerance',
    behavConservative: 'Conservative',
    behavModerate: 'Moderate',
    behavAggressive: 'Aggressive',
    behavPsychProfile: 'Psychological Profile',
    behavLossQ: 'If your portfolio lost 20% in a month, how would you react?',
    behavLossR1: 'Sell everything immediately',
    behavLossR2: 'Wait and monitor carefully',
    behavLossR3: 'Buy more at a lower price',
    behavSocialQ: 'Do you make investment decisions based on social media trends?',
    behavSocialR1: 'Never, I do my own research',
    behavSocialR2: 'Sometimes for small amounts',
    behavSocialR3: 'Frequently to catch trends',
    behavKnowledgeQ: 'Rate your confidence in financial market knowledge (1-10)',
    behavKnowledgeRange: '1 = Novice, 10 = Expert',
    behavHoldingQ: 'What is your typical investment holding period?',
    behavHoldingR1: 'Less than 6 months',
    behavHoldingR2: '6 – 12 months',
    behavHoldingR3: 'More than 1 year',
    behavModrikNoteTitle: 'Modrik Engine',
    behavModrikNoteText: 'The Modrik neural engine analyzes your risk appetite and behavioral biases to construct a mathematically optimized portfolio tailored specifically to your psychological profile.',
    behavAnalyze: 'Analyze My Profile',
    behavAnalyzing: 'Analyzing...',
    behavResultTitle: 'Behavioral Score',
    behavResultBadge: 'Level: Excellent',
    behavResultDone: 'View Smart Insights',
    // Cash Flow Forecast page (separate from cashflow tab)
    cashFlowForecastTitle: 'Cash Flow Forecast',
    cashFlowInflows: 'INFLOWS',
    cashFlowOutflows: 'OUTFLOWS',
    cashFlowNetFlow: 'NET FLOW',
    cashFlowPositive: 'Positive',
    cashFlowChartTitle: 'Cash Flow Chart',
    cashFlowLegendInflows: 'Inflows',
    cashFlowLegendOutflows: 'Outflows',
    cashFlowInflowSources: 'Inflow Sources',
    cashFlowOutflowCat: 'Outflow Categories',
    cashFlowModrikInsight: 'Modrik AI Insight',
    cashFlowInsightBody: 'A 4.2% declining trend is expected next 30 days due to seasonal supplier payments. Your strong inflow coverage ratio (1.27x) means your business remains liquid. Consider delaying non-critical purchases to preserve SAR 45,000+ in operating buffer.',
    cashFlowClientRevenue: 'Client Revenue',
    cashFlowServiceFees: 'Service Fees',
    cashFlowInvestments: 'Investments',
    cashFlowPayroll: 'Payroll',
    cashFlowSuppliers: 'Suppliers',
    cashFlowOperations: 'Operations',
    cashFlowOther: 'Other',
    // ── Personal Information ────────────────────────────────────────────────
    piTitle: 'Personal Information',
    piFirstName: 'First Name',
    piLastName: 'Last Name',
    piEmail: 'Email Address',
    piEmailNote: 'Email address cannot be changed',
    piMobile: 'Mobile Number',
    piNationalId: 'National ID / Iqama',
    piSave: 'Save Changes',
    piSaved: 'Changes saved!',
    // ── Cards Management ───────────────────────────────────────────────────
    cardsTitle: 'Cards Management',
    cardsMyCards: 'My Cards',
    cardsAddCard: 'Add New Card',
    cardsExpires: 'Expires',
    cardsFreeze: 'Freeze',
    cardsUnfreeze: 'Unfreeze',
    cardsFrozen: 'Frozen',
    cardsRemove: 'Remove Card',
    cardsRemoveConfirm: 'Remove this card from your account?',
    cardsAddSoon: 'Card linking will be available soon.',
    // ── Privacy & Security ─────────────────────────────────────────────────
    psTitle: 'Privacy & Security',
    psChangePassSection: 'Change Password',
    psBioSection: 'Biometric Login',
    psBioDesc: 'Use fingerprint or Face ID to sign in',
    psTfaSection: 'Two-Factor Authentication',
    psTfaDesc: 'Add an extra layer of account security',
    psCurrentPass: 'Current Password',
    psNewPass: 'New Password',
    psConfirmPass: 'Confirm New Password',
    psSavePass: 'Update Password',
    psPassMismatch: 'Passwords do not match',
    psPassTooShort: 'Password must be at least 6 characters',
    psPassUpdated: 'Password updated successfully!',
    psWrongCurrent: 'Current password is incorrect',
    psDangerZone: 'Danger Zone',
    psDeleteAcct: 'Delete Account',
    psDeleteMsg: 'Permanently delete your account and all data. This cannot be undone.',
    // ── Notification Settings ──────────────────────────────────────────────
    notifSetTitle: 'Notification Settings',
    notifSetAll: 'All Notifications',
    notifSetAllDesc: 'Master toggle — enable or disable all',
    notifSetPush: 'Push Notifications',
    notifSetPushDesc: 'Alerts and reminders on your device',
    notifSetEmail: 'Email Alerts',
    notifSetEmailDesc: 'Receive updates by email',
    notifSetFinancial: 'Financial Alerts',
    notifSetFinancialDesc: 'Transactions and balance changes',
    notifSetAi: 'AI Insights',
    notifSetAiDesc: 'Modrik recommendations and signals',
    notifSetMarket: 'Market Updates',
    notifSetMarketDesc: 'Daily financial market summaries',
    notifSetSecurity: 'Security Alerts',
    notifSetSecurityDesc: 'Sign-in attempts and account events',
    notifSetSaved: 'Preferences saved',
    // ── Language Settings ──────────────────────────────────────────────────
    langSettingsTitle: 'Language',
    langSelect: 'Select Language',
    langEnglish: 'English',
    langArabic: 'العربية',
    langEnDesc: 'Left-to-right · Default',
    langArDesc: 'Arabic · Right-to-left',
    langActive: 'Active',
    // ── Technical Support ─────────────────────────────────────────────────
    suppTitle: 'Technical Support',
    suppFaqSection: 'Frequently Asked Questions',
    suppContactSection: 'Contact Us',
    suppEmailLabel: 'Email Support',
    suppEmailDesc: 'We respond within 24 hours',
    suppPhoneLabel: 'Phone Support',
    suppPhoneDesc: 'Sun–Thu · 9AM–5PM AST',
    suppMsgSection: 'Send a Message',
    suppSubjectPh: 'Subject',
    suppMsgPh: 'Describe your issue...',
    suppSend: 'Send Message',
    suppSentMsg: "Message sent! We'll reply within 24 hours.",
    suppFaqQ1: 'How do I reset my password?',
    suppFaqA1: 'Go to Settings → Privacy & Security → Change Password.',
    suppFaqQ2: 'How do I switch between Business and Personal mode?',
    suppFaqA2: 'Open Settings and tap "Switch to Business Mode" or "Switch to Personal Mode".',
    suppFaqQ3: 'How do I export a financial report?',
    suppFaqA3: 'Open the Analytics tab → AI Report → Export PDF.',
    suppFaqQ4: 'Is my financial data secure?',
    suppFaqA4: 'Yes. All data is encrypted with bank-grade AES-256 encryption.',
    suppFaqQ5: 'How do I add or remove a card?',
    suppFaqA5: 'Go to Settings → Cards Management.',
    // ── Company Details ────────────────────────────────────────────────────
    cdTitle: 'Company Details',
    cdCompanyName: 'Company Name',
    cdCrNumber: 'CR Number',
    cdTaxNumber: 'VAT / Tax Number',
    cdIndustry: 'Industry',
    cdAddress: 'Business Address',
    cdSave: 'Save Changes',
    cdSaved: 'Changes saved!',
    // ── Payment Methods ────────────────────────────────────────────────────
    pmTitle: 'Payment Methods',
    pmAdd: 'Add Payment Method',
    pmNone: 'No payment methods added yet.',
    pmDefault: 'Default',
    pmSetDefault: 'Set as Default',
    pmRemove: 'Remove',
    // ── Billing & Invoices ─────────────────────────────────────────────────
    billTitle: 'Billing & Invoices',
    billPlanSection: 'Current Plan',
    billPlanName: 'Madarik Business Pro',
    billPlanPrice: 'SAR 299 / month',
    billNextDate: 'Next billing date',
    billManagePlan: 'Manage Plan',
    billHistory: 'Invoice History',
    billDownload: 'Download',
    billNoInvoices: 'No invoices yet.',
    // ── Investments screen ─────────────────────────────────────────────────
    investTitle: 'Investments',
    investPortfolio: 'Portfolio Value',
    investHoldings: 'My Holdings',
    investAddInv: 'Add Investment',
    // ── Savings screen ─────────────────────────────────────────────────────
    savingsTitle: 'Savings',
    savingsTotal: 'Total Savings',
    savingsGoals: 'Savings Goals',
    savingsAddGoal: 'Add New Goal',
    // Tab bar navigation
    tabHome: 'Home',
    tabDashboard: 'Dashboard',
    tabCashFlow: 'Cash Flow',
    tabModrik: 'Modrik',
    tabInsights: 'Insights',
    tabAnalytics: 'Analytics',
    tabProfile: 'Profile',
    tabSettings: 'Settings',
    // Smart Insights screen (Personal)
    insightsTitle: 'Smart Insights',
    insightsBehaviorScore: 'AI Behavior Score',
    insightsMonthlyAssess: 'Monthly Assessment',
    insightsLevelExcellent: 'Level: Excellent',
    insightsStability: 'STABILITY',
    insightsDiscipline: 'DISCIPLINE',
    insightsRiskProfile: 'Risk Profile',
    insightsModerate: 'Moderate',
    insightsMediumRisk: 'Medium Risk',
    insightsConfidence: 'Confidence',
    insightsEmotionDetect: 'Emotion Detection',
    insightsRationalDec: 'Rational Decisions',
    insightsPanicSell: 'Panic Selling',
    insightsFOMO: 'FOMO Detected',
    insightsOverconf: 'Overconfidence',
    insightsAiInsightLabel: 'AI Insight:',
    insightsAiInsightText: 'Recent activity suggests emotional trading after short-term market fluctuations in the tech sector.',
    insightsSpendAnalysis: 'Spending Analysis',
    insightsMonthlyTag: 'MONTHLY',
    insightsSavingsRate: 'Savings\nRate',
    insightsTotalExp: 'Total Expenses',
    insightsFood: 'Food',
    insightsShopping: 'Shopping',
    insightsBills: 'Bills',
    insightsInvestActivity: 'Investment Activity',
    insightsBuySell: 'BUY VS SELL',
    insightsHorizon: 'HORIZON',
    insightsLong: 'Long',
    insightsShort: 'Short',
    insightsBuyCount: '24 Buy',
    insightsSellCount: '3 Sell',
    insightsPortfolioGrowth: 'PORTFOLIO GROWTH',
    insightsRecommendations: 'Recommendations',
    insightsSmartPlan: 'Smart Plan',
    insightsSuggestedAlloc: 'SUGGESTED ALLOCATION',
    insightsMonthlyTarget: 'MONTHLY TARGET',
    insightsRiskAdjust: 'RISK ADJUST',
    insightsFinGoals: 'Financial Goals',
    insightsEmergencyFund: 'Emergency\nFund',
    insightsInvestGoal: 'Investment\nGoal',
    insightsSavingsGoalLabel: 'Savings\nGoal',
    insightsUpdateAssess: 'Update Behavioral Assessment',
    insightsScoreQuote: '"Your investment decisions have been consistent and emotionally balanced this month. Keep it up!"',
  },
  ar: {
    // Mode select
    modeSelectTag: 'أهلاً بك في مدارك',
    modeSelectTitle: 'اختر مسارك',
    modeSelectSub: 'حدد التجربة التي تناسب أهدافك المالية. يمكنك التبديل في أي وقت من ملفك الشخصي.',
    businessTitle: 'مدارك للأعمال',
    businessDesc: 'إدارة التدفق النقدي للشركة، الخدمات المصرفية التجارية، الإيرادات والمصروفات بالذكاء الاصطناعي.',
    businessF1: 'تحليلات التدفق النقدي',
    businessF2: 'الخدمات المصرفية',
    businessF3: 'مستشار مالي ذكي',
    personalTitle: 'مدارك الشخصي',
    personalDesc: 'الاستثمار الذكي، التقييم السلوكي بالذكاء الاصطناعي، اكتشاف المشاعر وإدارة البطاقات الشخصية.',
    personalF1: 'التقييم السلوكي',
    personalF2: 'تتبع المحفظة',
    personalF3: 'رؤى ذكية',
    modeFooter: 'موثوق به من قبل أكثر من 2,400 شركة ومستثمر في المملكة العربية السعودية',
    // Login
    loginTitle: 'تسجيل الدخول',
    loginUserPlaceholder: 'اسم المستخدم أو الهوية',
    loginPassPlaceholder: 'كلمة المرور',
    loginRemember: 'تذكرني',
    loginBtn: 'دخول',
    loginForgot: 'نسيت بيانات الدخول؟',
    loginNoAccount: 'ليس لديك حساب؟',
    loginSignUp: ' سجّل الآن',
    loginContact: 'تواصل معنا',
    loginCopyright: 'مدارك 2026. جميع الحقوق محفوظة',
    // Signup
    signupTitle: 'إنشاء حساب',
    signupNationalId: 'رقم الهوية الوطنية / الإقامة',
    signupNationalIdPh: 'أدخل رقم هويتك',
    signupMobile: 'رقم الجوال',
    signupEmail: 'البريد الإلكتروني',
    signupEmailPh: 'أدخل بريدك الإلكتروني',
    signupFirstName: 'الاسم الأول',
    signupLastName: 'اسم العائلة',
    signupUsername: 'اسم المستخدم',
    signupUsernamePh: 'أدخل اسم المستخدم',
    signupPassword: 'كلمة المرور',
    signupPasswordPh: 'أدخل كلمة المرور',
    signupAgree: 'أوافق على الشروط والأحكام وأؤكد أنني قرأت وفهمت إشعار الخصوصية',
    signupBtn: 'تسجيل',
    signupHaveAccount: 'لديك حساب بالفعل؟',
    signupLogin: ' سجّل دخولك',
    // Signup validation errors
    validRequired: 'هذا الحقل مطلوب',
    validNationalIdDigits: 'يجب أن تحتوي الهوية على أرقام فقط',
    validNationalIdMin: 'يجب أن تكون الهوية 10 أرقام على الأقل',
    validNationalIdTaken: 'رقم الهوية هذا مسجّل مسبقاً',
    validEmailFormat: 'يرجى إدخال بريد إلكتروني صحيح (مثال: name@domain.com)',
    validEmailTaken: 'هذا البريد الإلكتروني مسجّل مسبقاً',
    validMobileDigits: 'يجب أن يحتوي الجوال على أرقام فقط',
    validMobileLen: 'يجب أن يكون رقم الجوال 9 أرقام ويبدأ بـ 5',
    validMobileTaken: 'رقم الجوال هذا مسجّل مسبقاً',
    validUsernameChars: 'يُسمح فقط بالحروف والأرقام والشرطة السفلية — لا مسافات أو رموز',
    validUsernameTaken: 'اسم المستخدم هذا محجوز مسبقاً',
    validPassLen: 'كلمة المرور يجب أن تكون 8 أحرف على الأقل',
    validPassUpper: 'يجب أن تحتوي على حرف كبير (A-Z)',
    validPassLower: 'يجب أن تحتوي على حرف صغير (a-z)',
    validPassDigit: 'يجب أن تحتوي على رقم (0-9)',
    validPassSpecial: 'يجب أن تحتوي على رمز خاص (مثل !@#$%)',
    // Modes
    businessMode: 'وضع الأعمال',
    personalMode: 'الوضع الشخصي',
    // Settings — shared
    settingsLanguage: 'اللغة',
    settingsLanguageValue: 'العربية',
    settingsNotifications: 'الإشعارات',
    settingsLogout: 'تسجيل الخروج',
    settingsSignOut: 'تسجيل الخروج',
    settingsSwitchBusiness: 'التحويل إلى وضع الأعمال',
    settingsSwitchPersonal: 'التحويل إلى الوضع الشخصي',
    settingsReferral: 'رمز الإحالة',
    settingsVersion: 'مدارك v1.0.0',
    settingsSupport: 'الدعم الفني',
    settingsHelp: 'المساعدة',
    // Settings — Personal
    settingsPersonalInfo: 'المعلومات الشخصية',
    settingsCards: 'إدارة البطاقات',
    settingsPrivacy: 'الخصوصية والأمان',
    settingsBehavioral: 'التقييم السلوكي',
    settingsProfileTitle: 'الملف الشخصي',
    // Settings — Business
    settingsAccount: 'الحساب',
    settingsCompanyDetails: 'تفاصيل الشركة',
    settingsPaymentMethods: 'طرق الدفع',
    settingsBilling: 'الفواتير',
    settingsPreferences: 'التفضيلات',
    settingsCurrency: 'العملة',
    settingsSecurity: 'الأمان',
    settingsChangePassword: 'تغيير كلمة المرور',
    settingsBiometric: 'تسجيل الدخول البيومتري',
    settingsTwoFactor: 'المصادقة الثنائية',
    // Home — Personal
    homeGoodMorning: 'صباح الخير',
    homeWelcomeBack: 'مرحباً بعودتك،',
    homeBalance: 'الرصيد الإجمالي',
    homePortfolio: 'المحفظة',
    homeRecentTx: 'المعاملات الأخيرة',
    homeViewAll: 'عرض الكل',
    homeInvest: 'الاستثمارات',
    homeScore: 'التقييم السلوكي',
    homeSavings: 'المدخرات',
    homeCards: 'بطاقاتي',
    // Home — Business
    homeRevenue: 'الإيرادات',
    homeExpenses: 'المصروفات',
    homeCashflow: 'التدفق النقدي',
    homePayments: 'المدفوعات القادمة',
    homeActivity: 'النشاط الأخير',
    homeTotalBal: 'إجمالي رصيد الأعمال',
    homeHealthScore: 'نقاط الصحة',
    homeAccounts: 'الحسابات',
    homeAlerts: 'التنبيهات',
    // AI / Modrik screen
    aiOnline: 'محلل ذكي · متصل',
    aiAnalyzing: 'محلل ذكي · يحلل معنويات السوق...',
    aiTypePlaceholder: 'اسأل مدرك أي شيء...',
    aiTypePlaceholderPersonal: 'اكتب رسالة، أو اسأل مدرك عن أصولك...',
    aiVolatilityAlert: 'مدرك: تم رصد تقلب في السوق. الاستقرار العاطفي: 88%',
    aiProtect: 'حماية',
    aiCalculating: 'مدرك يحسب المخاطر...',
    aiToday: 'اليوم',
    aiPersonalQ1: 'نعم، احمِ محفظتي',
    aiPersonalQ2: 'عرض السجل',
    aiPersonalQ3: 'تحدث معي',
    aiPersonalQ4: 'تقييمي السلوكي',
    aiBusinessQ1: 'تحليل التدفق النقدي',
    aiBusinessQ2: 'تقليل المصروفات',
    aiBusinessQ3: 'أهلية القرض',
    aiBusinessQ4: 'توقعات الإيرادات',
    // Analytics screen
    analyticsTitle: 'التحليلات',
    analyticsSubtitle: 'نظرة مالية · يوليو 2026',
    analyticsRevenue: 'الإيرادات',
    analyticsExpenses: 'المصروفات',
    analyticsNetProfit: 'صافي الربح',
    analyticsRevenueTrend: 'اتجاه الإيرادات',
    analyticsExpenseBreakdown: 'تفصيل المصروفات',
    analyticsHealthScore: 'مؤشر صحة الأعمال',
    analyticsHealthDesc: 'أداء ممتاز هذا الربع',
    analyticsGrossMargin: 'هامش الربح الإجمالي',
    analyticsNetMargin: 'هامش الربح الصافي',
    analyticsROI: 'العائد على الاستثمار',
    analyticsBurnRate: 'معدل الإنفاق',
    analyticsPayroll: 'الرواتب',
    analyticsOperations: 'العمليات',
    analyticsSuppliers: 'الموردون',
    analyticsRentUtil: 'الإيجار والمرافق',
    analyticsOther: 'أخرى',
    // Cash Flow screen
    cashflowTitle: 'التدفق النقدي',
    cashflowSubtitle: 'توقعات 30 يوم',
    cashflowExportPDF: 'تصدير PDF',
    cashflowMonthlyInflow: 'التدفق الداخل الشهري',
    cashflowMonthlyOutflow: 'التدفق الخارج الشهري',
    cashflowNetMonth: 'الصافي هذا الشهر',
    cashflow30DayLabel: 'توقعات الصافي 30 يوم:',
    cashflowPositiveSurplus: 'فائض إيجابي متوقع',
    cashflow6Month: 'التدفق النقدي 6 أشهر',
    cashflowInflow: 'داخل',
    cashflowOutflow: 'خارج',
    cashflowRevenueUp: 'الإيرادات ارتفعت 12% مقارنة بالربع الماضي',
    cashflowModrikRec: 'توصية مدرك الذكي',
    cashflowModrikBody: 'فائض متوقع 45,000 ريال الشهر القادم. فكر في نقله إلى حساب أعمال عالي العائد لتحسين رأس المال العامل. مدتك النقدية صحية بـ 4.2 شهر.',
    cashflowAskModrik: 'اسأل مدرك للتفاصيل',
    cashflowApplyFinancing: 'تقدم\nللتمويل',
    cashflowAIRec: 'توصيات\nالذكاء',
    cashflowFinancialReport: 'التقرير\nالمالي',
    cashflowAskModrikShort: 'اسأل\nمدرك',
    // Notifications
    notifTitle: 'الإشعارات',
    notifMarkAllRead: 'تحديد الكل كمقروء',
    notifSearchPh: 'البحث في الإشعارات...',
    notifFilterAll: 'الكل',
    notifFilterEmotional: 'عاطفي',
    notifFilterInsights: 'رؤى',
    notifFilterTransact: 'معاملات',
    notifRecentActivity: 'النشاط الأخير',
    notifUnread: 'غير مقروء',
    notifEmpty: 'لا توجد إشعارات',
    // AI Recommendations
    aiRecTitle: 'توصيات الذكاء الاصطناعي',
    aiRecHighImpact: 'تأثير عالٍ',
    aiRecMedium: 'متوسط',
    aiRecInformational: 'معلوماتي',
    aiRecTakeAction: 'اتخذ إجراء',
    aiRecImpactHigh: 'تأثير عالٍ',
    aiRecImpactMedium: 'تأثير متوسط',
    aiRecImpactLow: 'تأثير منخفض',
    // AI Alerts
    aiAlertsTitle: 'التنبيهات',
    aiAlertsCritical: 'حرج',
    aiAlertsWarning: 'تحذير',
    aiAlertsInfo: 'معلومة',
    // AI Report
    aiReportTitle: 'التقرير المالي الذكي',
    aiReportHealthScore: 'مؤشر صحة الأعمال',
    aiReportHealthDesc: 'ممتاز · أفضل 15% من الشركات',
    aiReportMonthlyRevenue: 'الإيرادات الشهرية',
    aiReportExportPDF: 'تصدير التقرير كاملاً (PDF)',
    aiReportGrossRevenue: 'إجمالي الإيرادات',
    aiReportNetRevenue: 'صافي الإيرادات',
    aiReportTotalExpenses: 'إجمالي المصروفات',
    aiReportNetProfit: 'صافي الربح',
    aiReportProfitMargin: 'هامش الربح',
    aiReportCashOnHand: 'النقد المتاح',
    aiReportExecSummary: 'الملخص التنفيذي',
    aiReportRevenueAnalysis: 'تحليل الإيرادات',
    aiReportExpenseReview: 'مراجعة المصروفات',
    aiReportCashFlowLiq: 'التدفق النقدي والسيولة',
    aiReportQ4Outlook: 'توقعات الربع الرابع 2026',
    // Loan Review
    loanTitle: 'مراجعة القرض',
    loanReviewOffer: 'مراجعة العرض',
    loanPreQualified: 'مؤهل مسبقاً',
    loanTotalAmount: 'إجمالي مبلغ القرض',
    loanAmountSub: 'معتمد للتوسع والنمو',
    loanInterestRate: 'معدل الفائدة',
    loanFixedAnnual: 'سنوي ثابت',
    loanTermPeriod: 'مدة القرض',
    loanMonthlyInst: 'أقساط شهرية',
    loanMonthly: 'شهرياً',
    loanDueOn5th: 'يستحق في الخامس',
    loanTotalCost: 'التكلفة الإجمالية',
    loanIncProcessing: 'شامل 0% رسوم',
    loanGuaranteeTitle: 'ضمان مدارك',
    loanGuaranteeSub: 'شروط شفافة، لا رسوم خفية.',
    loanG1: 'لا غرامات سداد مبكر',
    loanG2: 'سداد تلقائي من التوقعات',
    loanG3: 'تحويل فوري عند التأكيد',
    loanG4: 'عقد رقمي بتوقيع إلكتروني',
    loanContinue: 'المتابعة للتأكيد',
    loanBackRec: 'العودة للتوصيات',
    // Upcoming Payments
    upcomingTitle: 'المدفوعات القادمة',
    upcomingTotalDue: 'إجمالي المستحق هذا الشهر',
    upcomingUrgentBadge: 'عاجل',
    upcomingFilterAll: 'الكل',
    upcomingFilterUrgent: 'عاجل',
    upcomingFilterUpcoming: 'قادم',
    // Accounts
    accountsTitle: 'حسابات الأعمال',
    accountsWelcomeSub: 'إدارة جميع حسابات أعمالك في مكان واحد.',
    accountsTotalBalance: 'إجمالي رصيد الأعمال',
    accountsAvailCash: 'النقد المتاح',
    accountsTodayChange: 'تغيير اليوم',
    accountsTransfer: 'تحويل',
    accountsTransactions: 'المعاملات',
    accountsAccountInfo: 'بيانات الحساب',
    accountsStatements: 'الكشوفات',
    accountsYourAccounts: 'حساباتك',
    accountsViewAll: 'عرض الكل',
    accountsCurrBalance: 'الرصيد الحالي',
    accountsActive: 'نشط',
    accountsLastTx: 'آخر معاملة',
    accountsInterestEarned: 'الفائدة المكتسبة',
    accountsNextPayroll: 'الرواتب القادمة',
    accountsAvailCredit: 'الائتمان المتاح',
    accountsNeedHelp: 'تحتاج مساعدة في حساباتك؟',
    accountsHelpDesc: 'اسأل مدرك عن التدفق النقدي أو سجل المعاملات.',
    accountsAskBtn: 'اسأل مدرك',
    // Behavioral Assessment
    behavTitle: 'تقييم السلوك',
    behavSub: 'أجب على بعض الأسئلة حتى يتمكن مدرك من فهم سلوكك المالي وتقديم توصيات استثمارية مخصصة.',
    behavFinancialProfile: 'الملف المالي',
    behavMonthlyIncome: 'الدخل الشهري',
    behavMonthlyExpenses: 'المصروفات الشهرية',
    behavCurrentSavings: 'المدخرات الحالية',
    behavCurrentInvestment: 'الاستثمار الحالي',
    behavInvExp: 'خبرة الاستثمار',
    behavBeginner: 'مبتدئ',
    behavIntermediate: 'متوسط',
    behavAdvanced: 'متقدم',
    behavInvGoal: 'هدف الاستثمار',
    behavGoal1: 'نمو الثروة',
    behavGoal2: 'التقاعد',
    behavGoal3: 'صندوق الطوارئ',
    behavGoal4: 'الدخل السلبي',
    behavGoal5: 'التعليم',
    behavRiskTolerance: 'تحمّل المخاطر',
    behavConservative: 'محافظ',
    behavModerate: 'معتدل',
    behavAggressive: 'عدواني',
    behavPsychProfile: 'الملف النفسي',
    behavLossQ: 'إذا خسرت محفظتك 20% في شهر، كيف ستتصرف؟',
    behavLossR1: 'بيع كل شيء فوراً',
    behavLossR2: 'الانتظار والمراقبة بعناية',
    behavLossR3: 'شراء المزيد بسعر أقل',
    behavSocialQ: 'هل تتخذ قرارات استثمارية بناءً على اتجاهات وسائل التواصل؟',
    behavSocialR1: 'أبداً، أقوم ببحثي الخاص',
    behavSocialR2: 'أحياناً لمبالغ صغيرة',
    behavSocialR3: 'كثيراً لاستغلال الاتجاهات',
    behavKnowledgeQ: 'قيّم ثقتك في معرفة الأسواق المالية (1-10)',
    behavKnowledgeRange: '1 = مبتدئ، 10 = خبير',
    behavHoldingQ: 'ما هي فترة الاحتفاظ النموذجية لاستثماراتك؟',
    behavHoldingR1: 'أقل من 6 أشهر',
    behavHoldingR2: '6 – 12 شهراً',
    behavHoldingR3: 'أكثر من سنة',
    behavModrikNoteTitle: 'محرك مدرك',
    behavModrikNoteText: 'يحلل محرك مدرك العصبي شهيتك للمخاطر وتحيزاتك السلوكية لبناء محفظة محسّنة رياضياً مصمّمة خصيصاً لملفك النفسي.',
    behavAnalyze: 'تحليل ملفي',
    behavAnalyzing: 'جارٍ التحليل...',
    behavResultTitle: 'التقييم السلوكي',
    behavResultBadge: 'المستوى: ممتاز',
    behavResultDone: 'عرض الرؤى الذكية',
    // Cash Flow Forecast page
    cashFlowForecastTitle: 'توقعات التدفق النقدي',
    cashFlowInflows: 'التدفقات الداخلة',
    cashFlowOutflows: 'التدفقات الخارجة',
    cashFlowNetFlow: 'الصافي',
    cashFlowPositive: 'إيجابي',
    cashFlowChartTitle: 'مخطط التدفق النقدي',
    cashFlowLegendInflows: 'داخل',
    cashFlowLegendOutflows: 'خارج',
    cashFlowInflowSources: 'مصادر التدفق الداخل',
    cashFlowOutflowCat: 'فئات التدفق الخارج',
    cashFlowModrikInsight: 'رؤية مدرك الذكية',
    cashFlowInsightBody: 'انخفاض بنسبة 4.2% متوقع خلال 30 يوماً بسبب مدفوعات الموردين الموسمية. نسبة تغطية التدفقات القوية (1.27x) تضمن سيولة أعمالك. فكر في تأجيل المشتريات غير الحيوية للحفاظ على 45,000+ ريال كاحتياطي تشغيلي.',
    cashFlowClientRevenue: 'إيرادات العملاء',
    cashFlowServiceFees: 'رسوم الخدمات',
    cashFlowInvestments: 'الاستثمارات',
    cashFlowPayroll: 'الرواتب',
    cashFlowSuppliers: 'الموردون',
    cashFlowOperations: 'العمليات',
    cashFlowOther: 'أخرى',
    // ── Personal Information ────────────────────────────────────────────────
    piTitle: 'المعلومات الشخصية',
    piFirstName: 'الاسم الأول',
    piLastName: 'اسم العائلة',
    piEmail: 'البريد الإلكتروني',
    piEmailNote: 'لا يمكن تغيير البريد الإلكتروني',
    piMobile: 'رقم الجوال',
    piNationalId: 'رقم الهوية / الإقامة',
    piSave: 'حفظ التغييرات',
    piSaved: 'تم الحفظ!',
    // ── Cards Management ───────────────────────────────────────────────────
    cardsTitle: 'إدارة البطاقات',
    cardsMyCards: 'بطاقاتي',
    cardsAddCard: 'إضافة بطاقة جديدة',
    cardsExpires: 'تنتهي',
    cardsFreeze: 'تجميد',
    cardsUnfreeze: 'إلغاء التجميد',
    cardsFrozen: 'مجمّدة',
    cardsRemove: 'حذف البطاقة',
    cardsRemoveConfirm: 'هل تريد حذف هذه البطاقة من حسابك؟',
    cardsAddSoon: 'ميزة ربط البطاقات ستكون متاحة قريباً.',
    // ── Privacy & Security ─────────────────────────────────────────────────
    psTitle: 'الخصوصية والأمان',
    psChangePassSection: 'تغيير كلمة المرور',
    psBioSection: 'تسجيل الدخول البيومتري',
    psBioDesc: 'استخدم بصمة الإصبع أو Face ID للدخول',
    psTfaSection: 'المصادقة الثنائية',
    psTfaDesc: 'طبقة حماية إضافية للحساب',
    psCurrentPass: 'كلمة المرور الحالية',
    psNewPass: 'كلمة المرور الجديدة',
    psConfirmPass: 'تأكيد كلمة المرور الجديدة',
    psSavePass: 'تحديث كلمة المرور',
    psPassMismatch: 'كلمتا المرور غير متطابقتين',
    psPassTooShort: 'يجب أن تكون 6 أحرف على الأقل',
    psPassUpdated: 'تم تحديث كلمة المرور!',
    psWrongCurrent: 'كلمة المرور الحالية غير صحيحة',
    psDangerZone: 'منطقة الخطر',
    psDeleteAcct: 'حذف الحساب',
    psDeleteMsg: 'حذف حسابك وجميع بياناتك نهائياً. لا يمكن التراجع.',
    // ── Notification Settings ──────────────────────────────────────────────
    notifSetTitle: 'إعدادات الإشعارات',
    notifSetAll: 'جميع الإشعارات',
    notifSetAllDesc: 'تفعيل أو تعطيل جميع التنبيهات',
    notifSetPush: 'الإشعارات الفورية',
    notifSetPushDesc: 'تنبيهات على جهازك',
    notifSetEmail: 'تنبيهات البريد',
    notifSetEmailDesc: 'تحديثات عبر البريد الإلكتروني',
    notifSetFinancial: 'التنبيهات المالية',
    notifSetFinancialDesc: 'المعاملات وتغييرات الرصيد',
    notifSetAi: 'رؤى الذكاء الاصطناعي',
    notifSetAiDesc: 'توصيات مدرك وإشاراته',
    notifSetMarket: 'تحديثات السوق',
    notifSetMarketDesc: 'ملخصات السوق المالي اليومية',
    notifSetSecurity: 'تنبيهات الأمان',
    notifSetSecurityDesc: 'تسجيلات الدخول وأحداث الحساب',
    notifSetSaved: 'تم حفظ التفضيلات',
    // ── Language Settings ──────────────────────────────────────────────────
    langSettingsTitle: 'اللغة',
    langSelect: 'اختر اللغة',
    langEnglish: 'English',
    langArabic: 'العربية',
    langEnDesc: 'من اليسار إلى اليمين',
    langArDesc: 'العربية · من اليمين إلى اليسار',
    langActive: 'نشط',
    // ── Technical Support ─────────────────────────────────────────────────
    suppTitle: 'الدعم الفني',
    suppFaqSection: 'الأسئلة الشائعة',
    suppContactSection: 'تواصل معنا',
    suppEmailLabel: 'الدعم عبر البريد',
    suppEmailDesc: 'نرد خلال 24 ساعة',
    suppPhoneLabel: 'الدعم الهاتفي',
    suppPhoneDesc: 'الأحد–الخميس · 9ص–5م',
    suppMsgSection: 'أرسل رسالة',
    suppSubjectPh: 'الموضوع',
    suppMsgPh: 'صِف مشكلتك...',
    suppSend: 'إرسال الرسالة',
    suppSentMsg: 'تم الإرسال! سنرد عليك خلال 24 ساعة.',
    suppFaqQ1: 'كيف أعيد تعيين كلمة المرور؟',
    suppFaqA1: 'اذهب إلى الإعدادات ← الخصوصية والأمان ← تغيير كلمة المرور.',
    suppFaqQ2: 'كيف أبدّل بين وضع الأعمال والشخصي؟',
    suppFaqA2: 'افتح الإعدادات واضغط على "التحويل إلى وضع الأعمال" أو "التحويل إلى الوضع الشخصي".',
    suppFaqQ3: 'كيف أصدّر تقريراً مالياً؟',
    suppFaqA3: 'اذهب إلى التحليلات ← التقرير الذكي ← تصدير PDF.',
    suppFaqQ4: 'هل بياناتي المالية آمنة؟',
    suppFaqA4: 'نعم. جميع البيانات مشفّرة بتشفير AES-256 من مستوى البنوك.',
    suppFaqQ5: 'كيف أضيف أو أحذف بطاقة؟',
    suppFaqA5: 'اذهب إلى الإعدادات ← إدارة البطاقات.',
    // ── Company Details ────────────────────────────────────────────────────
    cdTitle: 'تفاصيل الشركة',
    cdCompanyName: 'اسم الشركة',
    cdCrNumber: 'رقم السجل التجاري',
    cdTaxNumber: 'رقم الضريبة / القيمة المضافة',
    cdIndustry: 'القطاع',
    cdAddress: 'عنوان الشركة',
    cdSave: 'حفظ التغييرات',
    cdSaved: 'تم الحفظ!',
    // ── Payment Methods ────────────────────────────────────────────────────
    pmTitle: 'طرق الدفع',
    pmAdd: 'إضافة طريقة دفع',
    pmNone: 'لم تتم إضافة طرق دفع بعد.',
    pmDefault: 'افتراضي',
    pmSetDefault: 'تعيين كافتراضي',
    pmRemove: 'حذف',
    // ── Billing & Invoices ─────────────────────────────────────────────────
    billTitle: 'الفواتير',
    billPlanSection: 'الخطة الحالية',
    billPlanName: 'مدارك للأعمال المتقدم',
    billPlanPrice: '٢٩٩ ريال / شهرياً',
    billNextDate: 'تاريخ الفوترة القادم',
    billManagePlan: 'إدارة الخطة',
    billHistory: 'سجل الفواتير',
    billDownload: 'تحميل',
    billNoInvoices: 'لا توجد فواتير بعد.',
    // ── Investments screen ─────────────────────────────────────────────────
    investTitle: 'الاستثمارات',
    investPortfolio: 'قيمة المحفظة',
    investHoldings: 'محفظتي',
    investAddInv: 'إضافة استثمار',
    // ── Savings screen ─────────────────────────────────────────────────────
    savingsTitle: 'المدخرات',
    savingsTotal: 'إجمالي المدخرات',
    savingsGoals: 'أهداف الادخار',
    savingsAddGoal: 'إضافة هدف جديد',
    // Tab bar navigation
    tabHome: 'الرئيسية',
    tabDashboard: 'لوحة التحكم',
    tabCashFlow: 'التدفق النقدي',
    tabModrik: 'مدرك',
    tabInsights: 'رؤى',
    tabAnalytics: 'التحليلات',
    tabProfile: 'الملف الشخصي',
    tabSettings: 'الإعدادات',
    // Smart Insights screen (Personal)
    insightsTitle: 'رؤى ذكية',
    insightsBehaviorScore: 'درجة السلوك الذكي',
    insightsMonthlyAssess: 'التقييم الشهري',
    insightsLevelExcellent: 'المستوى: ممتاز',
    insightsStability: 'الاستقرار',
    insightsDiscipline: 'الانضباط',
    insightsRiskProfile: 'ملف المخاطر',
    insightsModerate: 'معتدل',
    insightsMediumRisk: 'مخاطر متوسطة',
    insightsConfidence: 'الثقة',
    insightsEmotionDetect: 'رصد المشاعر',
    insightsRationalDec: 'قرارات عقلانية',
    insightsPanicSell: 'بيع الهلع',
    insightsFOMO: 'خشية الفوات',
    insightsOverconf: 'ثقة زائدة',
    insightsAiInsightLabel: 'رؤية مدرك:',
    insightsAiInsightText: 'تشير الأنشطة الأخيرة إلى تداول عاطفي بعد تقلبات السوق قصيرة الأمد في قطاع التقنية.',
    insightsSpendAnalysis: 'تحليل الإنفاق',
    insightsMonthlyTag: 'شهري',
    insightsSavingsRate: 'نسبة\nالادخار',
    insightsTotalExp: 'إجمالي النفقات',
    insightsFood: 'طعام',
    insightsShopping: 'تسوق',
    insightsBills: 'فواتير',
    insightsInvestActivity: 'نشاط الاستثمار',
    insightsBuySell: 'شراء / بيع',
    insightsHorizon: 'الأفق',
    insightsLong: 'طويل',
    insightsShort: 'قصير',
    insightsBuyCount: '24 شراء',
    insightsSellCount: '3 بيع',
    insightsPortfolioGrowth: 'نمو المحفظة',
    insightsRecommendations: 'التوصيات',
    insightsSmartPlan: 'الخطة الذكية',
    insightsSuggestedAlloc: 'التوزيع المقترح',
    insightsMonthlyTarget: 'الهدف الشهري',
    insightsRiskAdjust: 'تعديل المخاطر',
    insightsFinGoals: 'الأهداف المالية',
    insightsEmergencyFund: 'صندوق\nالطوارئ',
    insightsInvestGoal: 'هدف\nالاستثمار',
    insightsSavingsGoalLabel: 'هدف\nالادخار',
    insightsUpdateAssess: 'تحديث التقييم السلوكي',
    insightsScoreQuote: '"قراراتك الاستثمارية كانت متسقة ومتوازنة عاطفياً هذا الشهر. استمر!"',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: TranslationKey) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  // Load persisted language on mount
  useEffect(() => {
    AsyncStorage.getItem(LANG_KEY)
      .then(val => { if (val === 'en' || val === 'ar') setLanguage(val); })
      .catch(() => {});
  }, []);

  const toggleLanguage = useCallback(() => {
    setLanguage(l => {
      const next = l === 'en' ? 'ar' : 'en';
      AsyncStorage.setItem(LANG_KEY, next).catch(() => {});
      return next;
    });
  }, []);

  const t = useCallback(
    (key: TranslationKey): string => translations[language][key] as string,
    [language],
  );

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t, isRTL: language === 'ar' }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
